"""`surrogate_key`: a Delta IDENTITY column (GENERATED BY DEFAULT) on an
scd1/scd2 dimension, first in the table, with -1 for the unknown member."""

from typing import Any

import pytest

from pipetree.adapters.spark import merge as merge_module
from pipetree.adapters.spark.adapter import SparkAdapter
from pipetree.adapters.spark.merge import (
    SurrogateKeyError,
    merge_scd1,
    merge_scd2,
    seed_unknown_member,
)
from pipetree.model import Table

pytestmark = pytest.mark.spark


def make_table(name: str, strategy: str, **overrides: Any) -> Table:
    raw: dict[str, Any] = {
        "name": name,
        "layer": "sk",
        "table_schema": f"sk_{strategy}",
        "fqn": f"sk_{strategy}.{name}",
        "strategy": strategy,
        "business_key": ["id"],
        "surrogate_key": "sid",
        **overrides,
    }
    return Table.model_validate(raw)


def df(spark, rows, ddl="id STRING, name STRING"):
    # One partition: Delta hands out identity values in blocks per task, so
    # a multi-partition insert leaves (documented, harmless) gaps.
    return spark.createDataFrame(rows, ddl).coalesce(1)


def sids(spark, fqn, where="true"):
    return {(r["id"], r["name"]): r["sid"] for r in spark.table(fqn).filter(where).collect()}


def table_features(spark, fqn):
    return set(spark.sql(f"DESCRIBE DETAIL {fqn}").collect()[0]["tableFeatures"])


@pytest.mark.parametrize("strategy", ["scd1", "scd2"])
def test_creates_the_table_with_an_identity_column_first(spark, strategy):
    table = make_table("create1", strategy)
    merge_fn = merge_scd1 if strategy == "scd1" else merge_scd2

    merge_fn(spark, table, df(spark, [("A", "a"), ("B", "b")]), 1, "crm")

    written = spark.table(table.fqn)
    assert written.columns[0] == "sid"
    assert written.columns[1:3] == ["id", "name"]
    assert "_execution_id" in written.columns
    assert "identityColumns" in table_features(spark, table.fqn)
    assert sorted(r["sid"] for r in written.collect()) == [1, 2]


def test_scd1_new_key_gets_a_new_sid_and_an_update_keeps_it(spark):
    table = make_table("scd1a", "scd1")
    merge_scd1(spark, table, df(spark, [("A", "a"), ("B", "b")]), 1, "crm")
    before = sids(spark, table.fqn)

    merge_scd1(spark, table, df(spark, [("A", "a2"), ("B", "b"), ("C", "c")]), 2, "crm")

    after = sids(spark, table.fqn)
    assert after[("A", "a2")] == before[("A", "a")]
    assert after[("B", "b")] == before[("B", "b")]
    assert after[("C", "c")] > max(before.values())
    assert len(after) == 3


def test_scd2_a_new_version_gets_a_new_sid_and_the_old_version_keeps_its_own(spark):
    table = make_table("scd2a", "scd2")
    merge_scd2(spark, table, df(spark, [("A", "a"), ("B", "b")]), 1, "crm")
    before = sids(spark, table.fqn)

    merge_scd2(spark, table, df(spark, [("A", "a2"), ("B", "b")]), 2, "crm")

    closed = sids(spark, table.fqn, "NOT _is_current")
    current = sids(spark, table.fqn, "_is_current")
    assert closed == {("A", "a"): before[("A", "a")]}
    assert current[("B", "b")] == before[("B", "b")]
    assert current[("A", "a2")] > max(before.values())


def test_unknown_member_gets_sid_minus_one_without_shifting_generation(spark):
    table = make_table("unk1", "scd1", unknown_member=True)
    merge_scd1(spark, table, df(spark, [], "id STRING, name STRING"), 1, "crm")
    seed_unknown_member(spark, table, execution_id=1)

    merge_scd1(spark, table, df(spark, [("A", "a"), ("B", "b"), ("C", "c")]), 2, "crm")
    seed_unknown_member(spark, table, execution_id=2)

    written = spark.table(table.fqn).collect()
    assert sorted(r["sid"] for r in written) == [-1, 1, 2, 3]
    unknown = [r for r in written if r["sid"] == -1]
    assert len(unknown) == 1
    assert unknown[0]["id"] is None  # NULL sentinel for a string business key


@pytest.mark.parametrize("strategy", ["scd1", "scd2"])
def test_a_second_identical_run_neither_renumbers_nor_duplicates(spark, strategy):
    table = make_table("idem1", strategy, unknown_member=True)
    merge_fn = merge_scd1 if strategy == "scd1" else merge_scd2
    source = [("A", "a"), ("B", "b")]

    merge_fn(spark, table, df(spark, source), 1, "crm")
    seed_unknown_member(spark, table, execution_id=1)
    first = sorted((r["sid"], r["id"]) for r in spark.table(table.fqn).collect())
    merge_fn(spark, table, df(spark, source), 2, "crm")
    seed_unknown_member(spark, table, execution_id=2)
    second = sorted((r["sid"], r["id"]) for r in spark.table(table.fqn).collect())

    assert second == first
    assert len({sid for sid, _ in second}) == 3


def test_schema_policy_fail_does_not_see_the_surrogate_key_as_drift(spark):
    table = make_table("drift1", "scd1", schema_policy="fail")
    merge_scd1(spark, table, df(spark, [("A", "a")]), 1, "crm")

    result = merge_scd1(spark, table, df(spark, [("A", "a2")]), 2, "crm")

    assert "schema_changes" not in result
    assert sids(spark, table.fqn) == {("A", "a2"): 1}


def test_schema_evolution_adds_a_column_after_the_identity(spark):
    table = make_table("drift2", "scd1")
    merge_scd1(spark, table, df(spark, [("A", "a")]), 1, "crm")

    merge_scd1(
        spark,
        table,
        df(spark, [("A", "a", "x"), ("B", "b", "y")], "id STRING, name STRING, extra STRING"),
        2,
        "crm",
    )

    rows = {r["id"]: r for r in spark.table(table.fqn).collect()}
    assert rows["A"]["sid"] == 1
    assert rows["B"]["sid"] > 1
    assert rows["B"]["extra"] == "y"


@pytest.mark.parametrize("strategy", ["scd1", "scd2"])
def test_a_source_that_already_has_the_surrogate_key_column_is_rejected(spark, strategy):
    table = make_table("srcsid", strategy)
    merge_fn = merge_scd1 if strategy == "scd1" else merge_scd2

    with pytest.raises(SurrogateKeyError, match="already has a column named 'sid'"):
        merge_fn(
            spark, table, df(spark, [(7, "A", "a")], "sid BIGINT, id STRING, name STRING"), 1, "c"
        )


def test_a_table_created_before_surrogate_key_was_set_fails_clearly(spark):
    plain = make_table("pre1", "scd1", surrogate_key=None)
    merge_scd1(spark, plain, df(spark, [("A", "a")]), 1, "crm")

    with pytest.raises(SurrogateKeyError, match="drop and recreate"):
        merge_scd1(spark, make_table("pre1", "scd1"), df(spark, [("A", "a2")]), 2, "crm")


def test_an_existing_plain_column_of_that_name_is_not_an_identity_column(spark):
    table = make_table("pre2", "scd1")
    spark.sql("CREATE SCHEMA IF NOT EXISTS sk_scd1")
    df(spark, [(1, "A", "a")], "sid BIGINT, id STRING, name STRING").write.format(
        "delta"
    ).saveAsTable(table.fqn)

    with pytest.raises(SurrogateKeyError, match="not an identity column"):
        merge_scd1(spark, table, df(spark, [("A", "a2")]), 2, "crm")


def test_init_on_a_surrogate_table_reloads_without_reusing_sids(spark):
    table = make_table("init1", "scd1")
    merge_scd1(spark, table, df(spark, [("A", "a"), ("B", "b")]), 1, "crm")

    merge_scd1(spark, table, df(spark, [("C", "c")]), 2, "crm", init=True)

    written = spark.table(table.fqn).collect()
    assert [r["id"] for r in written] == ["C"]
    assert written[0]["sid"] > 2  # the high-water mark survives; no sid is reused
    assert spark.table(table.fqn).columns[0] == "sid"


def test_composite_business_key_with_a_surrogate_and_unknown_member(spark):
    table = make_table("comp1", "scd2", business_key=["id", "region"], unknown_member=True)
    ddl = "id INT, region STRING, name STRING"
    merge_scd2(spark, table, df(spark, [(1, "eu", "a"), (1, "us", "b")], ddl), 1, "crm")
    seed_unknown_member(spark, table, execution_id=1)
    merge_scd2(spark, table, df(spark, [(1, "eu", "a2"), (1, "us", "b")], ddl), 2, "crm")
    seed_unknown_member(spark, table, execution_id=2)

    rows = spark.table(table.fqn).collect()
    unknown = [r for r in rows if r["sid"] == -1]
    assert len(unknown) == 1
    assert (unknown[0]["id"], unknown[0]["region"]) == (-1, None)
    assert len({r["sid"] for r in rows}) == len(rows) == 4  # 2 + 1 new version + unknown


def test_unsupported_identity_columns_raise_a_clear_error(spark, monkeypatch):
    def unsupported(*_args, **_kwargs):
        raise RuntimeError("[UNSUPPORTED_FEATURE.TABLE_OPERATION] does not support identity")

    monkeypatch.setattr(merge_module, "_create_identity_table_with_builder", unsupported)
    monkeypatch.setattr(merge_module, "_create_identity_table_with_sql", unsupported)
    table = make_table("unsupported1", "scd1")

    with pytest.raises(SurrogateKeyError, match=r"identity columns.*Delta Lake 3\.3"):
        merge_scd1(spark, table, df(spark, [("A", "a")]), 1, "crm")
    assert not spark.catalog.tableExists(table.fqn)


# ------------------------------------------------- through the adapter


def _adapter_table(**overrides: Any) -> Table:
    raw: dict[str, Any] = {
        "name": "dim_product",
        "layer": "gold",
        "table_schema": "sk_gold",
        "fqn": "sk_gold.dim_product",
        "strategy": "scd2",
        "business_key": ["product_code"],
        "surrogate_key": "product_sid",
        "unknown_member": True,
        "logic": "dim.sql",
        **overrides,
    }
    return Table.model_validate(raw)


def test_layered_dim_with_sid_stripping_null_keys_and_unknown_member(spark, tmp_path):
    adapter = SparkAdapter(spark, systems={}, base_dir=tmp_path)
    (tmp_path / "bronze.sql").write_text(
        "SELECT 'P1' AS product_code, 'Pen' AS name "
        "UNION ALL SELECT 'P2', 'Pad' UNION ALL SELECT CAST(NULL AS STRING), 'Nothing'"
    )
    bronze = _adapter_table(
        name="product",
        layer="bronze",
        table_schema="sk_bronze",
        fqn="sk_bronze.product",
        strategy="replace",
        business_key=[],
        surrogate_key=None,
        unknown_member=False,
        logic="bronze.sql",
    )
    adapter.run_table(bronze, execution_id=1)
    (tmp_path / "dim.sql").write_text("SELECT * FROM sk_bronze.product")
    dim = _adapter_table()

    first = adapter.run_table(dim, execution_id=2)
    snapshot = sorted((r["product_sid"], r["product_code"]) for r in spark.table(dim.fqn).collect())
    second = adapter.run_table(dim, execution_id=3)

    assert first is not None and first["null_keys_dropped"] == 1
    assert second is not None and second["null_keys_dropped"] == 1
    rows = spark.table(dim.fqn).collect()
    assert sorted((r["product_sid"], r["product_code"]) for r in rows) == snapshot
    assert spark.table(dim.fqn).columns[0] == "product_sid"
    unknown = [r for r in rows if r["product_sid"] == -1]
    assert len(unknown) == 1 and unknown[0]["product_code"] is None
    assert {r["_execution_id"] for r in rows if r["product_sid"] != -1} == {2}


def test_downstream_select_star_from_a_dim_carries_the_sid_as_an_ordinary_column(spark, tmp_path):
    adapter = SparkAdapter(spark, systems={}, base_dir=tmp_path)
    (tmp_path / "dim.sql").write_text("SELECT 'P1' AS product_code, 'Pen' AS name")
    dim = _adapter_table(fqn="sk_gold.dim_product2", name="dim_product2")
    adapter.run_table(dim, execution_id=1)

    (tmp_path / "copy.sql").write_text("SELECT * FROM sk_gold.dim_product2")
    copy = _adapter_table(
        fqn="sk_gold.dim_product2_copy",
        name="dim_product2_copy",
        strategy="scd1",
        surrogate_key=None,
        unknown_member=False,
        business_key=["product_sid"],
        logic="copy.sql",
    )
    adapter.run_table(copy, execution_id=2)
    adapter.run_table(copy, execution_id=3)

    copied = {r["product_sid"]: r["product_code"] for r in spark.table(copy.fqn).collect()}
    original = {r["product_sid"]: r["product_code"] for r in spark.table(dim.fqn).collect()}
    assert copied == original  # sid -1 / unknown included, carried as plain data

    # The same name as this table's own surrogate_key is a configuration error.
    clash = _adapter_table(
        fqn="sk_gold.dim_product2_clash", name="dim_product2_clash", logic="copy.sql"
    )
    with pytest.raises(SurrogateKeyError, match="already has a column named 'product_sid'"):
        adapter.run_table(clash, execution_id=4)


def test_a_fact_takes_the_dimension_sid_or_minus_one(spark, tmp_path):
    adapter = SparkAdapter(spark, systems={}, base_dir=tmp_path)
    (tmp_path / "dim.sql").write_text(
        "SELECT 'P1' AS product_code, 'Pen' AS name UNION ALL SELECT 'P2', 'Pad'"
    )
    dim = _adapter_table(fqn="sk_gold.dim_product3", name="dim_product3")
    adapter.run_table(dim, execution_id=1)
    spark.createDataFrame(
        [(1, "P1"), (2, "P2"), (3, "P9"), (4, None)], "sale_id INT, product_code STRING"
    ).createOrReplaceTempView("sk_fact_sales")

    fact = spark.sql(
        "SELECT f.sale_id, COALESCE(d.product_sid, -1) AS product_sid "
        "FROM sk_fact_sales f LEFT JOIN sk_gold.dim_product3 d "
        "ON f.product_code = d.product_code AND d._is_current = true"
    ).collect()

    dim_sids = {r["product_code"]: r["product_sid"] for r in spark.table(dim.fqn).collect()}
    assert sorted((r["sale_id"], r["product_sid"]) for r in fact) == [
        (1, dim_sids["P1"]),
        (2, dim_sids["P2"]),
        (3, -1),
        (4, -1),
    ]
