coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,files"
  require_changes: true
  hide_project_coverage: false

ignore:
  - "tests/**"
  - "examples/**"
  - "docs/**"
