"""The four merge strategies, against Delta: scd1, scd2, replace, append.

scd1/scd2 use Delta's merge builder. Delta's MERGE can only take one action
per matched row (update *or* delete, never "close this row and also insert
its replacement"), so scd2 runs in two passes: a merge that closes changed
or deleted current versions (and inserts brand-new keys), then a plain
INSERT of the new version for every key that actually changed - determined
from the *pre-merge* snapshot, materialized before the merge runs so it
isn't re-evaluated against the table the merge just mutated.
"""

from __future__ import annotations

import datetime
import logging
import operator
from decimal import Decimal
from functools import reduce
from typing import Any

from delta.tables import DeltaTable
from pyspark.sql import Column, DataFrame, Row, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegralType,
    NumericType,
    StringType,
    StructType,
    TimestampNTZType,
    TimestampType,
)

from pipetree.adapters.spark.audit import (
    insert_audit_values,
    scd2_close_values,
    scd2_insert_audit_values,
    update_audit_values,
)
from pipetree.adapters.spark.dedupe import dedupe_for_merge
from pipetree.executor.execution_id import timestamp_bigint
from pipetree.model import DELETE_MARKER_COLUMN, RESERVED_AUDIT_COLUMNS, Table
from pipetree.schema.infer import infer_schema
from pipetree.schema.policy import SchemaReconciliation, reconcile

_logger = logging.getLogger("pipetree.adapters.spark")

_IS_DELETE_COL = DELETE_MARKER_COLUMN

# pipetree's own stamps, never part of the source's schema: excluded when
# inferring a target table's schema for drift comparison, and stripped from
# an incoming source (see `strip_reserved_columns`).
_AUDIT_COLUMNS = RESERVED_AUDIT_COLUMNS

# The unknown member's surrogate key; generated ones start at 1.
UNKNOWN_MEMBER_SURROGATE_KEY = -1


class SurrogateKeyError(RuntimeError):
    """A `surrogate_key` table can't be written as configured: the source
    already carries the column, the existing table has no identity column,
    or the engine doesn't support Delta identity columns at all."""


def strip_reserved_columns(source: DataFrame, table: Table) -> DataFrame:
    """Drop pipetree's reserved audit columns from an incoming source.

    A downstream table built from an upstream pipetree table (`SELECT *
    FROM bronze.x`, or a DataFrame derived from `spark.table("bronze.x")`)
    inherits the upstream's `_execution_id`, `_inserted_at`, ... - which
    are never meaningful downstream: every strategy stamps its own, and
    stamping on top of an inherited one fails with COLUMN_ALREADY_EXISTS.
    Matched by exact name only, so a user's own `_`-prefixed column that
    isn't reserved passes through untouched.
    """
    reserved = [c for c in source.columns if c in _AUDIT_COLUMNS]
    if not reserved:
        return source
    _logger.debug(
        "%s: dropping reserved audit column(s) inherited from the source: %s",
        table.fqn,
        ", ".join(reserved),
    )
    return source.drop(*reserved)


def _reconcile_schema(
    spark: SparkSession, table: Table, deduped: DataFrame
) -> SchemaReconciliation:
    exclude = _AUDIT_COLUMNS
    if table.surrogate_key:
        # Generated by the table, never part of the source - not drift.
        exclude = exclude | {table.surrogate_key}
    target_schema = infer_schema(spark.table(table.fqn), exclude=exclude)
    source_schema = infer_schema(deduped)
    return reconcile(deduped.columns, source_schema, target_schema, table.schema_policy, table.fqn)


def merge_replace(
    spark: SparkSession,
    table: Table,
    source: DataFrame,
    execution_id: int,
    source_system: str | None,
    init: bool = False,  # noqa: ARG001 - replace always fully overwrites; init changes nothing
) -> dict:
    _ensure_schema(spark, table.fqn)
    now = timestamp_bigint()

    stamped = _with_values(source, insert_audit_values(execution_id, source_system, now))
    row_count = stamped.count()
    stamped.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
        table.fqn
    )
    return {"rows_written": row_count}


def merge_append(
    spark: SparkSession,
    table: Table,
    source: DataFrame,
    execution_id: int,
    source_system: str | None,
    init: bool = False,
) -> dict:
    _ensure_schema(spark, table.fqn)
    now = timestamp_bigint()

    stamped = _with_values(source, insert_audit_values(execution_id, source_system, now))
    row_count = stamped.count()
    # init is a full reload: start over even if the table already exists.
    mode = "overwrite" if init or not _table_exists(spark, table.fqn) else "append"
    stamped.write.format("delta").mode(mode).saveAsTable(table.fqn)
    return {"rows_written": row_count}


def merge_scd1(
    spark: SparkSession,
    table: Table,
    source: DataFrame,
    execution_id: int,
    source_system: str | None,
    init: bool = False,
) -> dict:
    _ensure_schema(spark, table.fqn)
    _reject_source_surrogate_key(source, table)
    now = timestamp_bigint()
    deduped, duplicates_dropped = dedupe_for_merge(_without_ignored_deletes(source, table), table)

    # init is a full reload: seed from scratch even if the table exists.
    if init or not _table_exists(spark, table.fqn):
        prepared = _prepare_source(deduped, table)
        seed = prepared.filter(~F.col(_IS_DELETE_COL)).drop(_IS_DELETE_COL)
        stamped = _with_values(seed, insert_audit_values(execution_id, source_system, now))
        row_count = stamped.count()
        _write_seed(spark, table, stamped)
        return {"rows_written": row_count, "duplicates_dropped": duplicates_dropped}

    _require_identity_column(spark, table)
    reconciliation = _reconcile_schema(spark, table, deduped)
    if reconciliation.columns != deduped.columns:
        deduped = deduped.select(*reconciliation.columns)
    columns = reconciliation.columns
    prepared = _prepare_source(deduped, table)

    key_cond = _key_condition(table)
    change_cond = _change_condition_sql(columns, table, reconciliation.target_columns)
    insert_values = _column_mapping(columns, insert_audit_values(execution_id, source_system, now))
    update_values = _column_mapping(columns, update_audit_values(execution_id, source_system, now))
    # A key that returns after a soft delete is active again (a returning soft-deleted key is active
    # again).
    update_values["_is_deleted"] = F.lit(False)

    delta_table = DeltaTable.forName(spark, table.fqn)
    merge_builder = delta_table.alias("target").merge(prepared.alias("source"), key_cond)

    if table.merge.delete_mode == "soft":
        soft_delete_values: dict[str, str | Column] = {
            **update_audit_values(execution_id, source_system, now),
            "_is_deleted": F.lit(True),
        }
        merge_builder = merge_builder.whenMatchedUpdate(
            # Deleting an already soft-deleted row is a no-op (re-runs are safe).
            condition=f"source.{_IS_DELETE_COL} = true AND target._is_deleted = false",
            set=soft_delete_values,
        )
    elif table.merge.delete_mode == "hard":
        merge_builder = merge_builder.whenMatchedDelete(condition=f"source.{_IS_DELETE_COL} = true")

    row_count = prepared.count()
    merge_builder = merge_builder.whenMatchedUpdate(
        condition=(
            f"source.{_IS_DELETE_COL} = false AND ({change_cond} OR target._is_deleted = true)"
        ),
        set=update_values,
    )
    in_place = _ignored_change_update(
        columns, table, reconciliation.target_columns, "target._is_deleted = false"
    )
    if in_place is not None:
        # Only ignored columns changed (ignore_columns alone update in place): written in place,
        # audit untouched.
        merge_builder = merge_builder.whenMatchedUpdate(condition=in_place[0], set=in_place[1])
    final_builder = merge_builder.whenNotMatchedInsert(
        condition=f"source.{_IS_DELETE_COL} = false", values=insert_values
    )
    if reconciliation.needs_schema_evolution:
        final_builder = final_builder.withSchemaEvolution()
    final_builder.execute()

    result: dict[str, Any] = {"rows_written": row_count, "duplicates_dropped": duplicates_dropped}
    if reconciliation.changes:
        result["schema_changes"] = [str(change) for change in reconciliation.changes]
    return result


def merge_scd2(
    spark: SparkSession,
    table: Table,
    source: DataFrame,
    execution_id: int,
    source_system: str | None,
    init: bool = False,
) -> dict:
    _ensure_schema(spark, table.fqn)
    _reject_source_surrogate_key(source, table)
    now = timestamp_bigint()
    deduped, duplicates_dropped = dedupe_for_merge(_without_ignored_deletes(source, table), table)

    # init is a full reload: seed from scratch (a fresh version-1 history)
    # even if the table already exists.
    if init or not _table_exists(spark, table.fqn):
        prepared = _prepare_source(deduped, table)
        seed = prepared.filter(~F.col(_IS_DELETE_COL)).drop(_IS_DELETE_COL)
        stamped = _with_values(seed, scd2_insert_audit_values(execution_id, source_system, now))
        row_count = stamped.count()
        _write_seed(spark, table, stamped)
        return {"rows_written": row_count, "duplicates_dropped": duplicates_dropped}

    _require_identity_column(spark, table)
    reconciliation = _reconcile_schema(spark, table, deduped)
    if reconciliation.columns != deduped.columns:
        deduped = deduped.select(*reconciliation.columns)
    columns = reconciliation.columns
    prepared = _prepare_source(deduped, table)

    not_deleted = prepared.filter(~F.col(_IS_DELETE_COL)).drop(_IS_DELETE_COL)
    current_before = spark.table(table.fqn).filter("_is_current = true")
    # Materialized now, before the merge below mutates the table this reads
    # from - otherwise a lazy re-evaluation after the merge would compare
    # against the already-closed rows instead of the pre-merge snapshot.
    # Pulled to the driver, not just cached: Delta's merge below writes to
    # the same table this reads from, and a write to a cataloged table
    # invalidates Spark's DataFrame cache for it - a merely .cache()'d plan
    # would silently recompute against the post-merge (already-closed) rows
    # the moment it's touched again. Demo-scale data only; a real dimension
    # table would need a different approach (see NOTES-for-blog.md).
    new_version_rows = _rows_that_changed(
        not_deleted, current_before, table, columns, reconciliation.target_columns
    ).collect()
    new_version_count = len(new_version_rows)
    new_versions_schema = not_deleted.select(*columns).schema

    key_cond = _key_condition(table) + " AND target._is_current = true"
    change_cond = _change_condition_sql(columns, table, reconciliation.target_columns)
    close_for_delete: dict[str, str | Column] = {
        **update_audit_values(execution_id, source_system, now),
        **scd2_close_values(now),
        "_is_deleted": F.lit(True),
    }
    close_for_change: dict[str, str | Column] = {
        **update_audit_values(execution_id, source_system, now),
        **scd2_close_values(now),
    }
    insert_new_key_values = _column_mapping(
        columns, scd2_insert_audit_values(execution_id, source_system, now)
    )

    row_count = prepared.count()
    delta_table = DeltaTable.forName(spark, table.fqn)
    merge_builder = (
        delta_table.alias("target")
        .merge(prepared.alias("source"), key_cond)
        .whenMatchedUpdate(condition=f"source.{_IS_DELETE_COL} = true", set=close_for_delete)
        .whenMatchedUpdate(
            condition=f"source.{_IS_DELETE_COL} = false AND ({change_cond})", set=close_for_change
        )
    )
    in_place = _ignored_change_update(columns, table, reconciliation.target_columns)
    if in_place is not None:
        # Only ignored columns changed (ignore_columns alone update in place): the CURRENT version
        # is updated
        # in place (the key condition only matches current rows); no new version.
        merge_builder = merge_builder.whenMatchedUpdate(condition=in_place[0], set=in_place[1])
    final_builder = merge_builder.whenNotMatchedInsert(
        condition=f"source.{_IS_DELETE_COL} = false", values=insert_new_key_values
    )
    if reconciliation.needs_schema_evolution:
        final_builder = final_builder.withSchemaEvolution()
    final_builder.execute()

    if new_version_count > 0:
        new_versions = spark.createDataFrame(new_version_rows, schema=new_versions_schema)
        stamped_new_versions = _with_values(
            new_versions, scd2_insert_audit_values(execution_id, source_system, now)
        )
        writer = stamped_new_versions.write.format("delta").mode("append")
        if reconciliation.needs_schema_evolution:
            writer = writer.option("mergeSchema", "true")
        writer.saveAsTable(table.fqn)
        row_count += new_version_count

    result: dict[str, Any] = {"rows_written": row_count, "duplicates_dropped": duplicates_dropped}
    if reconciliation.changes:
        result["schema_changes"] = [str(change) for change in reconciliation.changes]
    return result


def seed_unknown_member(spark: SparkSession, table: Table, execution_id: int) -> None:
    """Seed the unknown member so facts can resolve a missing foreign key to
    it instead of leaving a NULL. A no-op if the table doesn't ask for it,
    doesn't exist yet, or already has one.

    Every business key column gets a sentinel of its own type (see
    `unknown_member_key`): `-1` for a numeric key, SQL NULL for a string,
    1900-01-01 for a date or timestamp. Matching is null-safe throughout,
    so re-seeding never adds a second row; `drop_null_business_keys` keeps
    a source's own NULL keys from colliding with it."""
    if not table.unknown_member or not table.business_key:
        return
    if not _table_exists(spark, table.fqn):
        return

    existing = spark.table(table.fqn)
    schema = existing.schema
    sentinels = {k: unknown_member_key(schema[k].dataType, table.fqn) for k in table.business_key}
    if existing.filter(_is_unknown_member(table, schema, sentinels)).limit(1).count() > 0:
        return

    now = timestamp_bigint()
    values: dict[str, Any] = dict.fromkeys(f.name for f in schema.fields)
    values.update(sentinels)
    values.update(
        {
            "_inserted_at": now,
            "_updated_at": now,
            "_is_deleted": False,
            "_execution_id": execution_id,
        }
    )
    if table.surrogate_key and table.surrogate_key in values:
        # Explicit -1 into a GENERATED BY DEFAULT identity column: accepted,
        # and it leaves the identity high-water mark (1, 2, 3, ...) alone.
        values[table.surrogate_key] = UNKNOWN_MEMBER_SURROGATE_KEY
    if "_is_current" in values:
        values["_is_current"] = True
    if "_valid_from" in values:
        values["_valid_from"] = now

    row = Row(**{f.name: values[f.name] for f in schema.fields})
    spark.createDataFrame([row], schema=schema).write.format("delta").mode("append").saveAsTable(
        table.fqn
    )


def drop_null_business_keys(source: DataFrame, table: Table) -> tuple[DataFrame, int]:
    """Drop source rows whose NULL business key cannot be merged, returning
    how many were dropped (NULL business keys).

    - `unknown_member` table (any strategy): a row with a NULL in ANY key
      column. NULL is the unknown member's key for a string column, so such
      a row would be indistinguishable from it in a null-safe fact join.
    - `scd1`/`scd2` table without it: a single-column key that is NULL, or a
      composite key whose columns are ALL NULL. A NULL in just one component
      of a composite key is a value: the merge matches it null-safely, so
      the same key hits the same row in every batch.
    - `replace`/`append` without it: nothing - a NULL key is data there.

    A no-op (no count, no scan) when the table has nothing to drop."""
    if not table.business_key:
        return source, 0
    nulls = [F.col(k).isNull() for k in table.business_key]
    if table.unknown_member:
        drop = reduce(operator.or_, nulls)
        reason = "NULL is reserved for the unknown member on an unknown_member table"
    elif table.strategy in ("scd1", "scd2"):
        drop = reduce(operator.and_, nulls)
        reason = "a NULL business key cannot identify a row"
    else:
        return source, 0
    dropped = source.filter(drop).count()
    if dropped == 0:
        return source, 0
    _logger.warning(
        "%s: dropped %d source row(s) with a NULL business key (%s) - %s",
        table.fqn,
        dropped,
        ", ".join(table.business_key),
        reason,
    )
    return source.filter(~drop), dropped


def _is_unknown_member(table: Table, schema: StructType, sentinels: dict[str, Any]) -> Column:
    """Null-safe "is this row the unknown member?" across every key column."""
    current = reduce(
        operator.and_,
        [F.col(k).eqNullSafe(F.lit(v).cast(schema[k].dataType)) for k, v in sentinels.items()],
    )
    first, *rest = table.business_key
    if not rest or not isinstance(schema[first].dataType, NumericType):
        return current
    # Before per-column sentinels, a composite key got -1 in its first
    # column and NULL in the rest - still the unknown member after upgrade.
    legacy = reduce(
        operator.and_,
        [F.col(first).eqNullSafe(F.lit(-1).cast(schema[first].dataType))]
        + [F.col(k).isNull() for k in rest],
    )
    return current | legacy


def unknown_member_key(key_type: DataType, table_fqn: str) -> Any:
    """The unknown member's key value, in the business key's own type - the
    value a fact's `COALESCE(fk, <this>)` must use to resolve to it. `None`
    (SQL NULL) for a string key: a fact reaches it with a null-safe join
    (`<=>` / `eqNullSafe`), not `=`."""
    if isinstance(key_type, DecimalType):
        return Decimal(-1)
    if isinstance(key_type, FloatType | DoubleType):
        return -1.0
    if isinstance(key_type, IntegralType):
        return -1
    if isinstance(key_type, StringType):
        return None
    if isinstance(key_type, TimestampType | TimestampNTZType):
        return datetime.datetime(1900, 1, 1)
    if isinstance(key_type, DateType):
        return datetime.date(1900, 1, 1)
    raise ValueError(
        f"{table_fqn}: unknown_member has no sentinel for a "
        f"{key_type.simpleString()} business key (supported: numeric, string, "
        "date, timestamp)"
    )


def _reject_source_surrogate_key(source: DataFrame, table: Table) -> None:
    sk = table.surrogate_key
    if sk and sk.lower() in (c.lower() for c in source.columns):
        raise SurrogateKeyError(
            f"{table.fqn}: the source already has a column named {sk!r}, which is this "
            "table's surrogate_key - pipetree generates it. Leave it out of the logic "
            f"(e.g. SELECT * EXCEPT ({sk}) ...) or rename it."
        )


def _write_seed(spark: SparkSession, table: Table, stamped: DataFrame) -> None:
    """The scd1/scd2 first load (or `init` full reload) of `stamped`."""
    if not table.surrogate_key:
        stamped.write.format("delta").mode("overwrite").option(
            "overwriteSchema", "true"
        ).saveAsTable(table.fqn)
        return

    if _table_exists(spark, table.fqn):
        # init on an existing dimension: keep the table - and with it the
        # identity column and its high-water mark, so no sid is ever reused
        # for a different row. overwriteSchema would drop the identity.
        _require_identity_column(spark, table)
        stamped.write.format("delta").mode("overwrite").option("mergeSchema", "true").saveAsTable(
            table.fqn
        )
        return

    _create_identity_table(spark, table, stamped.schema)
    stamped.write.format("delta").mode("append").saveAsTable(table.fqn)


def _create_identity_table(spark: SparkSession, table: Table, schema: StructType) -> None:
    """Create the table with `<surrogate_key> BIGINT GENERATED BY DEFAULT AS
    IDENTITY (START WITH 1 INCREMENT BY 1)` first, then `schema`'s columns.

    Two routes, because engines differ: the DeltaTable builder (OSS
    delta-spark 3.3+; OSS's DeltaCatalog rejects the SQL DDL form) and the
    SQL DDL (Databricks). If neither works, the engine has no identity
    columns and that's said plainly instead of surfacing a raw Spark error."""
    sk = table.surrogate_key
    assert sk is not None
    errors: list[str] = []
    for create in (_create_identity_table_with_builder, _create_identity_table_with_sql):
        try:
            create(spark, table.fqn, sk, schema)
            return
        except Exception as exc:  # collected; re-raised below as one clear error
            errors.append(f"{type(exc).__name__}: {str(exc).splitlines()[0][:300]}")
    raise SurrogateKeyError(
        f"{table.fqn}: surrogate_key {sk!r} needs Delta identity columns (GENERATED BY "
        "DEFAULT AS IDENTITY), which this engine does not support - it needs Delta Lake "
        "3.3+ (OSS delta-spark, e.g. 4.0) or Databricks Runtime 10.4+; Fabric Runtime 1.3 "
        "(Delta 3.2) does not have them, and Microsoft's Fabric Delta-interoperability "
        "page lists identity-column writes as unsupported in Fabric. Underlying "
        "errors: " + " | ".join(errors)
    )


def _create_identity_table_with_builder(
    spark: SparkSession, fqn: str, sk: str, schema: StructType
) -> None:
    from delta.tables import IdentityGenerator  # delta-spark 3.3+

    builder = DeltaTable.create(spark).tableName(fqn)
    builder = builder.addColumn(
        sk, "BIGINT", generatedByDefaultAs=IdentityGenerator(start=1, step=1)
    )
    for field in schema.fields:
        builder = builder.addColumn(field.name, field.dataType, nullable=True)
    builder.execute()


def _create_identity_table_with_sql(
    spark: SparkSession, fqn: str, sk: str, schema: StructType
) -> None:
    columns = ", ".join(f"`{f.name}` {f.dataType.simpleString()}" for f in schema.fields)
    spark.sql(
        f"CREATE TABLE {fqn} (`{sk}` BIGINT GENERATED BY DEFAULT AS IDENTITY "
        f"(START WITH 1 INCREMENT BY 1), {columns}) USING DELTA"
    )


def _require_identity_column(spark: SparkSession, table: Table) -> None:
    """An existing table must already have the surrogate key as an identity
    column - Delta can't add one to an existing table, so a table created
    before `surrogate_key` was set fails here rather than being skipped."""
    sk = table.surrogate_key
    if not sk:
        return
    recreate = (
        "Delta cannot add an identity column to an existing table: drop and recreate the "
        "table (pipetree recreates it on the next run), then reload whatever references it."
    )
    if sk.lower() not in (c.lower() for c in spark.table(table.fqn).columns):
        raise SurrogateKeyError(
            f"{table.fqn}: surrogate_key {sk!r} is set, but the existing table has no such "
            f"column - it was created before surrogate_key was set. {recreate}"
        )
    detail = spark.sql(f"DESCRIBE DETAIL {table.fqn}").collect()[0].asDict()
    features = detail.get("tableFeatures")
    # The catalog's schema strips Delta's identity metadata, so the table
    # protocol is the portable signal: the `identityColumns` table feature,
    # or legacy writer version 6+ on an engine without table features.
    has_identity = (
        "identityColumns" in features
        if features is not None
        else (detail.get("minWriterVersion") or 0) >= 6
    )
    if not has_identity:
        raise SurrogateKeyError(
            f"{table.fqn}: column {sk!r} exists but is not an identity column. {recreate}"
        )


def _ensure_schema(spark: SparkSession, fqn: str) -> None:
    schema = fqn.split(".")[0]
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {schema}")


def _table_exists(spark: SparkSession, fqn: str) -> bool:
    return spark.catalog.tableExists(fqn)


def _with_values(df: DataFrame, values: dict) -> DataFrame:
    return df.select("*", *[value.alias(name) for name, value in values.items()])


def _column_mapping(
    source_columns: list, audit_values: dict[str, Column]
) -> dict[str, str | Column]:
    """`{col: "source.col", ...}` for every business column, plus the given
    audit columns - built as one literal so the merged dict's value type is
    `str | Column` throughout, matching what Delta's merge builder expects."""
    return {**{c: f"source.{c}" for c in source_columns}, **audit_values}


def _without_ignored_deletes(df: DataFrame, table: Table) -> DataFrame:
    """`delete_mode: ignore` drops the source's delete signal entirely: delete rows
    are removed before the duplicate resolution, as if they were not in the batch.
    A NULL `delete_when` result is not a delete (the row stays), as in `_prepare_source`."""
    if table.merge.delete_mode != "ignore" or not table.merge.delete_when:
        return df
    return df.filter(~F.coalesce(F.expr(table.merge.delete_when), F.lit(False)))


def _prepare_source(df: DataFrame, table: Table) -> DataFrame:
    if table.merge.delete_mode == "ignore" or not table.merge.delete_when:
        return df.withColumn(_IS_DELETE_COL, F.lit(False))
    return df.withColumn(_IS_DELETE_COL, F.expr(table.merge.delete_when))


def _key_condition(table: Table) -> str:
    return " AND ".join(f"target.{k} <=> source.{k}" for k in table.business_key)


def _comparable_columns(
    columns: list, table: Table, existing_columns: frozenset[str] | None = None
) -> list:
    candidates = [
        c for c in columns if c not in table.business_key and c not in table.merge.ignore_columns
    ]
    if existing_columns is not None:
        # A just-added column has no old value on the target side to
        # compare against - it can't inform "did this row change".
        candidates = [c for c in candidates if c in existing_columns]
    return candidates


def _ignored_columns(
    columns: list, table: Table, existing_columns: frozenset[str] | None = None
) -> list:
    """Ignored columns present in the source (and, when known, in the target:
    a just-added column has no old value to compare against)."""
    cols = [c for c in columns if c in table.merge.ignore_columns and c not in table.business_key]
    if existing_columns is not None:
        cols = [c for c in cols if c in existing_columns]
    return cols


def _ignored_change_update(
    columns: list,
    table: Table,
    existing_columns: frozenset[str] | None,
    extra_condition: str | None = None,
) -> tuple[str, dict[str, str | Column]] | None:
    """Condition and `set` for the in-place update of a matched row whose only
    change is in `ignore_columns` (ignore_columns alone update in place): the ignored columns are
    written,
    audit columns are not bumped. None when there is nothing to compare."""
    compare = _ignored_columns(columns, table, existing_columns)
    if not compare:
        return None
    differs = " OR ".join(f"NOT (target.{c} <=> source.{c})" for c in compare)
    condition = f"source.{_IS_DELETE_COL} = false"
    if extra_condition:
        condition += f" AND {extra_condition}"
    condition += f" AND ({differs})"
    # Written: every ignored column the source carries (even a just-added one).
    written = [
        c for c in columns if c in table.merge.ignore_columns and c not in table.business_key
    ]
    set_values: dict[str, str | Column] = {c: f"source.{c}" for c in written}
    return condition, set_values


def _change_condition_sql(
    columns: list, table: Table, existing_columns: frozenset[str] | None = None
) -> str:
    compare_cols = _comparable_columns(columns, table, existing_columns)
    if not compare_cols:
        # No tracked column: nothing can be a tracked change (an ignored-only
        # change is handled by `_ignored_change_update`).
        return "false"
    same = " AND ".join(f"target.{c} <=> source.{c}" for c in compare_cols)
    return f"NOT ({same})"


def _rows_that_changed(
    source_df: DataFrame,
    current_df: DataFrame,
    table: Table,
    columns: list,
    existing_columns: frozenset[str] | None = None,
) -> DataFrame:
    """Source rows whose business columns differ from their current target
    row - used to decide which keys need a new scd2 version opened."""
    compare_cols = _comparable_columns(columns, table, existing_columns)
    join_cond = [source_df[k].eqNullSafe(current_df[k]) for k in table.business_key]
    joined = source_df.join(current_df, join_cond, "inner")

    if not compare_cols:
        # No tracked column: never a tracked change (matches `_change_condition_sql`).
        return joined.filter(F.lit(False)).select(*[source_df[c] for c in columns])

    conditions = [~source_df[col].eqNullSafe(current_df[col]) for col in compare_cols]
    diff = reduce(operator.or_, conditions)

    return joined.filter(diff).select(*[source_df[c] for c in columns])
